ssh_hosts_key_file: '/root/.ssh/known_hosts'
host_etcd_port_number: 23790
logging: DEBUG
hpe3par_debug: True
suppress_requests_ssl_warning: True
#hpe3par_api_url = https://15.212.192.252:8080/api/v1
hpe3par_ip: 15.212.192.251
hpe3par_username: 3paradm
hpe3par_password: 3pardata
#san_ip: 15.212.192.252
san_login: 3paradm
san_password: 3pardata
hpe3par_cpg: FC_r1
hpe3par_snapcpg: FC_r1
hpe3par_iscsi_chap_enabled: True
#hpe3par_iscsi_ips: 15.212.192.112
use_multipath: True
enforce_multipath: True