---
- name: Deploy FlexVolume driver
  hosts: localhost
  become: no

  vars:
    driver_path: "/usr/libexec/kubernetes/kubelet-plugins/volume/exec/hpe.com~hpe/"

  vars_prompt:
    - name: "start_doryd"
      prompt: "Is this a master node? (yes/no)"
      private: no
      default: "no"

  tasks:
    - name: load etcd settings
      include_vars: 'properties/etcd_properties.yml'

    - name: Create FlexVolume driver directory
      file:
        path: {{ item }}
        state: directory
        mode: 0644
        recurse: yes
      with_items:
        - {{ driver_path }}
        - /etc/kubernetes/

    - name: Verify /etc/kubernetes/admin.conf exists
      copy:
        src: /root/.kube/config
        dest: /etc/kubernetes/admin.conf
        owner: root
        mode: 0755

    - name: Install FlexVolume drivers
      copy:
        src: "{{ item }}"
        dest: "{{ driver_path }}"
        owner: root
        mode: 0755
        with_fileglob:
          - /files/dory/*

    - name: Start Dynamic Provisioner (doryd) on Master node
      command: nohup {{ driver_path }} /root/.kube/config hpe.com &
      when: start_doryd == "yes"
